config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end
  resources :products

  # You can have the root of your site routed with "root"
  root 'store#index', as: 'store'
  # ...
end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
	<head>
		<!-- START_HIGHLIGHT -->
		<title>Pragprog Books Online Store</title>
		<!-- END_HIGHLIGHT -->
		<!-- <label id="code.slt"/> --><%= stylesheet_link_tag    "application", media: "all",
		"data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %><!-- <label id="code.jlt"/> -->
		<%= csrf_meta_tags %><!-- <label id="code.csrf"/> -->
	</head>
	<!-- END:head -->
	<body class="<%= controller.controller_name %>">
		<!-- START_HIGHLIGHT -->
		<div id="banner">
			<%= image_tag("logo.png", class: "logo") %>
			<%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
			<span class="cboth"></span>
		</div>
		<div id="columns">
			<div id="side">
				<!-- START:hidden_div -->
				<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				<%= render @cart %>
				<% end %>
				<% end %>
				<!-- END:hidden_div -->
				<ul>
					<li><%= link_to "Home", store_path %></li>
					<li><a href="#">Questions</a></li>
					<li><a href="#">News</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<% if session[:user_id] %>
				<ul>
					<li><%= link_to 'Orders', orders_path %></li>
					<li><%= link_to 'Products', products_path %></li>
					<li><%= link_to 'Users', users_path %></li>
				</ul>
				<%= button_to 'Logout', logout_path, method: :delete, class: 'btn_logout' %>
				<% else %>
				<%= button_to 'Admin Login', users_path, class: 'btn_login' %>
				<% end %>
			</div>
			<div id="main">
				<!-- END_HIGHLIGHT -->
				<%= yield %><!-- <label id="code.depot.e.include"/> -->
				<!-- START_HIGHLIGHT -->
			</div>
		</div>
		<!-- END_HIGHLIGHT -->
	</body>
</html>